name: Update Release Versions

on:
  release:
    types:
      - published

jobs:
  update_release_versions:
    uses: codenamephp/workflows.common/.github/workflows/updateReleaseVersions.yml@release
    with:
      version: ${{ github.event.release.tag_name }}
      release_ref: ${{ github.ref }}
